spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/notification_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}

notification:
  email:
    senders:
      gmail:
        host: smtp.gmail.com
        port: 587
        username: ${GMAIL_USERNAME:your-email@gmail.com}
        password: ${GMAIL_PASSWORD:your-app-password}
        properties:
          mail.smtp.auth: 'true'
          mail.smtp.starttls.enable: 'true'
      outlook:
        host: smtp-mail.outlook.com
        port: 587
        username: ${OUTLOOK_USERNAME:your-outlook@outlook.com}
        password: ${OUTLOOK_PASSWORD:your-outlook-password}
        properties:
          mail.smtp.auth: 'true'
          mail.smtp.starttls.enable: 'true'

  whatsapp:
    twilio:
      account-sid: ${TWILIO_ACCOUNT_SID:}
      auth-token: ${TWILIO_AUTH_TOKEN:}
      from-number: ${TWILIO_FROM_NUMBER:}

logging:
  level:
    com.notificationservice: DEBUG
    org.springframework.mail: DEBUG
