spring:
  application:
    name: notification-service

  datasource:
    url: jdbc:postgresql://localhost:5432/notification_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME:your-email@gmail.com}
    password: ${EMAIL_PASSWORD:your-app-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

# Email sender configurations
notification:
  email:
    senders:
      gmail:
        host: smtp.gmail.com
        port: 587
        username: ${GMAIL_USERNAME:your-gmail@gmail.com}
        password: ${GMAIL_PASSWORD:your-gmail-app-password}
        properties:
          mail.smtp.auth: true
          mail.smtp.starttls.enable: true
      outlook:
        host: smtp-mail.outlook.com
        port: 587
        username: ${OUTLOOK_USERNAME:your-outlook@outlook.com}
        password: ${OUTLOOK_PASSWORD:your-outlook-password}
        properties:
          mail.smtp.auth: true
          mail.smtp.starttls.enable: true
      custom:
        host: ${CUSTOM_SMTP_HOST:smtp.example.com}
        port: ${CUSTOM_SMTP_PORT:587}
        username: ${CUSTOM_SMTP_USERNAME:}
        password: ${CUSTOM_SMTP_PASSWORD:}
        properties:
          mail.smtp.auth: true
          mail.smtp.starttls.enable: true

  whatsapp:
    twilio:
      account-sid: ${TWILIO_ACCOUNT_SID:}
      auth-token: ${TWILIO_AUTH_TOKEN:}
      from-number: ${TWILIO_FROM_NUMBER:}

server:
  port: 8080

logging:
  level:
    com.notificationservice: DEBUG
    org.springframework.mail: DEBUG

# Rate Limiter Configuration
rate-limiter:
  enabled: true
  create:
    max-requests: 10
    window-minutes: 1
    timeout-seconds: 5
  read:
    max-requests: 100
    window-minutes: 1
    timeout-seconds: 2
  redirect:
    max-requests: 500
    window-minutes: 1
    timeout-seconds: 1
  analytics:
    max-requests: 30
    window-minutes: 1
    timeout-seconds: 3
  admin:
    max-requests: 20
    window-minutes: 1
    timeout-seconds: 5
